server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway