server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms1-coordenador-route
          uri: lb://MS1-COORDENADOR
          predicates:
            - Path=/chat/**