server:
  port: 8081

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/boletim}
    username: ${POSTGRES_USER:boletim}
    password: ${POSTGRES_PASSWORD:boletim}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always